### ISSUE TITLE
JOSS: Functionality documentation

### ISSUE THREAD

**Issue by abhiramm7** [LLNL/Abmarl#168]
Hi, I commend the authors on thorough documentation. In the JOSS paper submission, you mention that Abmarl integration with open ai gym and MultiAgentEnv. Having some documentation or a simple example on how users can interface with the two packages might be helpful.

**Comment by rusu24edward** [comment]
HI @abhiramm7 

Thank you for your insightful review. Regarding integration with `MultiAgentEnv` and `gym.Env`, we do have this documented in the API spec [here](https://abmarl.readthedocs.io/en/latest/api.html#abmarl.external.MultiAgentWrapper) and [here](https://abmarl.readthedocs.io/en/latest/api.html#abmarl.external.GymWrapper). Additionally, we the [MultiCorridor tutorial](https://abmarl.readthedocs.io/en/latest/tutorials/multi_corridor.html#simulation-setup) and [PredatorPrey tutorial](https://abmarl.readthedocs.io/en/latest/tutorials/predator_prey.html#experiment-parameters) show how to use the `MultiAgentWrapper` to treat the simulation as a `MultiAgentEnv`.

Does the documentation need to be clarified? Should I add another example using the GymWrapper?

**Comment by abhiramm7** [comment]
I see that the MultiCorridor uses gym.spaces. I was under the impression that abmarl would be able to wrap around an existing open ai gym environment. I apologize if I am mis-interpreting it. I was thinking an example that uses an existing open ai gym environment with abmarl would be helpful to users.

**Comment by rusu24edward** [comment]
Thanks for the clarification! I agree, this would be helpful. I'll add a page on running Abmarl with already-existing gym environments.

**Comment by rusu24edward** [comment]
@abhiramm7 Here is a brief demo for training a gym environment with abmarl: https://abmarl.readthedocs.io/en/latest/tutorials/gym.html
