### ISSUE TITLE
Use magical isinstance check to make Agent work with ActingAgent and ObservingAgent

### ISSUE THREAD

**Issue by rusu24edward** [LLNL/Abmarl#286]
There are a lot of times where we want to do `isinstance(obj, Agent)`, and what we mean is that we want to ensure that it has an observation space and an action space--that it is an `ObservingAgent` and an `ActingAgent`. This only works if the user explicitly makes his agents using the `Agent` class; if the user is using the GSF, the agents are *not* made using the `Agent` class, so all our checks have to be `isinstance(obj, ActingAgent) and isinstnace(obj, ObservingAgent)`, which is annoying.

The `__isinstancecheck__` built in allows us to overwrite the instance check.

**Comment by mojoee** [comment]
Hi @rusu24edward! Could you assign me this issue?

**Comment by mojoee** [comment]
Can you give me a pointer? I don't know where to start

**Comment by rusu24edward** [comment]
Sure thing. For background, we have two classes: [ObservingAgent](https://github.com/LLNL/Abmarl/blob/main/abmarl/sim/agent_based_simulation.py#L100) and [ActingAgent](https://github.com/LLNL/Abmarl/blob/main/abmarl/sim/agent_based_simulation.py#L61). Our package has subclasses of these individually to support common features. In addition, we have an [Agent](https://github.com/LLNL/Abmarl/blob/main/abmarl/sim/agent_based_simulation.py#L139) class, which is just a nice shortcut.

Throughout the code we check if an entity is *both* an ActingAgent and an ObservingAgent. We have to do that like this:
```
isinstance(obj, ObservingAgent) and isinstance(obj, ActingAgent)
```
This is a little annoying, and we would like to be able to do
```
isinstance(obj, Agent)
```
However, this currently doesn't work because many objects do not directly inherit from `Agent` but inherit from `ObservingAgent` and `ActingAgent`:
```
class Example1(Agent) # This will work with isinstance(obj, Agent)
class Example2(ObservingAgent, ActingAgent) # this will not work with isinstance(obj, Agent)
```

To overcome this annoyance, we can overwrite the `__instancecheck__` builtin function of the `Agent`.

Here's how I would approach this:
1. Overwrite `__instancecheck__` in the `Agent` class so that it works for objects that inherit from `ObservingAgent` and `ActingAgent`.
2. Grep the codebase looking for usage of `isinstance`: `grep -iRl 'isinstance' .`
3. Replace `isinstance(obj, ObservingAgent) and isisntance(obj, ActingAgent)` with `isinstance(obj, Agent)`.

**Comment by mojoee** [comment]
Thanks. Very clear instructions. I got it and made a PR
