### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by aowen87** [LLNL/Abmarl#368]
It looks like the newer versions of numpy have removed the ability to use `numpy.int`. This raises an error in Abmarl (stack trace below). This was using numpy version 1.24.2. Downgrading to 1.21.5 is a temporary fix.

```
...
  File "/.../site-packages/abmarl/sim/gridworld/observer.py", line 248, in __init__
    np.array([0, 0], dtype=np.int),
  File "/.../site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
```

**Comment by rusu24edward** [comment]
Add CI test using python 3.8
