### ISSUE TITLE
Update gym dependency

### ISSUE THREAD

**Issue by aowen87** [LLNL/Abmarl#375]
Would it be possible to update the gym version dependency? There are some conflicts between pip and older versions of gym that I'm seeing crop up in Github's CI.

**Comment by aowen87** [comment]
On second thought, this might be a bad idea. It seems like there are a lot of breaking changes in newer versions. I'll see if I can get Github to play nice.

**Comment by aowen87** [comment]
I'm re-opening this as I'm finding other dependencies are requiring a newer version of gym. It's not an immediate need, but it would be nice to have the upgrade at some point.

**Comment by rusu24edward** [comment]
> Temporary fix is to include `setuptools<67.0` at the top of the requirements file

This didn't work. Exploring down RLlib's rabbit hole, it looks like the best solution is to set numpy < 1.24.
