### ISSUE TITLE
Box compatibility 

### ISSUE THREAD

**Issue by aowen87** [LLNL/Abmarl#483]
It looks like the FlattenWrapper that Abmarl uses expects a specialized version of the Box space that's written in Abmarl, and it will fail in a very obscure way if you use a regular gym Box. I went down a rabbit hole tracking down the cause of this error... 

Can the FlattenWrapper (and anywhere else in Abmarl that expects this Abmarl version of Box) be updated to support gym's version of Box as well? If not, can Abmarl throw a useful error so that users can know to switch over to the Abmarl version of the Box space?

**Comment by rusu24edward** [comment]
Comes from #62
