### ISSUE TITLE
MultiAgentWrapper without RLLib

### ISSUE THREAD

**Issue by aowen87** [LLNL/Abmarl#491]
I recently tried to use Abmarl's MultiAgentWrapper without having installed RLLib and was surprised to see this error:
```
NotImplementedError: Cannot use MultiAgentWrapper without RLlib. Please install the RLlib extra with, for example, pip install abmarl[rllib].
```

Is there a reason for this dependency? Can it be removed?

**Comment by aowen87** [comment]
Looking a bit at the code, it looks like this wrapper is made specifically for RLLib. It would be great if there was a generic wrapper that enforced this interface since it's fairly common. I'll see if I can just make my own simple interface in the meantime.

**Comment by rusu24edward** [comment]
Why not just use the Simulation Manager as is?

**Comment by aowen87** [comment]
Well, fixing that gym compatibility issue seems to have resolved everything! I'll go ahead and close this since it seems irrelevant now.
